In [49]:
from sklearn.pipeline import Pipeline
##feature Scaling
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression

In [50]:
steps=[("standard_scler",StandardScaler()),
       ("classifer",LogisticRegression())]

In [51]:
steps

[('standard_scler', StandardScaler()), ('classifer', LogisticRegression())]

In [52]:
pipe=Pipeline(steps)

In [53]:
#visualize Pipeline
from sklearn import set_config
set_config(display="diagram")

In [54]:
pipe

Pipeline(steps=[('standard_scler', StandardScaler()),
                ('classifer', LogisticRegression())])

In [55]:
#create dataset
from sklearn.datasets import make_classification
x,y=make_classification(n_samples=100)

In [56]:
x,y

(array([[-0.23863267,  0.4073936 ,  1.77529018, ...,  0.19126104,
          1.2306166 , -1.78753688],
        [ 0.7988178 ,  1.63729679, -1.68457274, ..., -1.80339719,
          1.2445261 , -1.52933462],
        [-1.42040311,  1.18459778,  0.10378819, ..., -1.06842642,
          1.01525589, -1.23573075],
        ...,
        [ 0.97775912, -2.38179632,  1.00413236, ...,  0.67597106,
         -1.21164958,  0.79323884],
        [ 0.46150465,  0.60373731,  0.70205694, ...,  0.06005238,
         -0.18168557,  0.52259489],
        [ 1.32235035,  1.66095267, -1.58117262, ...,  0.92075139,
         -0.16000794, -1.12083554]]),
 array([1, 1, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1,
        0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0,
        0, 1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 0, 0, 0, 1,
        0, 1, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1,
        1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1]))

In [57]:
x.shape

(100, 20)

In [58]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.33,random_state=42)

In [59]:
len(x_train),len(x_test)

(67, 33)

In [60]:
pipe.fit(x_train,y_train)

Pipeline(steps=[('standard_scler', StandardScaler()),
                ('classifer', LogisticRegression())])

In [61]:
y_pred=pipe.predict(x_test)

In [62]:
y_pred

array([0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 1, 1,
       1, 0, 0, 0, 0, 1, 0, 1, 1, 1, 1])

<h1>Example 2</h1>
**Displaying a pipeline with standard scaler,dimenionality reduction and then estimator**

In [63]:
from sklearn.decomposition import PCA
from sklearn.svm import SVC

In [64]:
steps=[("scaling",StandardScaler()),
       ("PCA",PCA(n_components=3)),
       ("classifier",SVC())]
steps

[('scaling', StandardScaler()),
 ('PCA', PCA(n_components=3)),
 ('classifier', SVC())]

In [65]:
from sklearn import set_config
set_config(display="diagram")

In [66]:
pipe2=Pipeline(steps)
pipe2

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('classifier', SVC())])

In [67]:
pipe2['scaling'].fit_transform(x_train)

array([[ 0.742264  , -1.59533887, -0.37960027, ..., -1.6233237 ,
        -0.5366662 , -0.44333551],
       [ 0.39189996,  0.17327632, -0.41116518, ..., -0.88014937,
        -0.02030516, -1.01155434],
       [-0.50693297,  1.06611372, -0.46065447, ...,  0.26955918,
         0.04425961, -1.26872479],
       ...,
       [ 0.38863201,  0.38105425, -0.52119998, ...,  0.83941984,
         0.13643482, -0.16056429],
       [-1.9119724 , -1.6261559 , -1.69092545, ..., -0.40702563,
         0.05392466, -0.14286889],
       [ 1.47390921,  1.53580057, -0.73780385, ...,  0.32792905,
        -1.11209794,  0.59731316]])

In [68]:
pipe2.fit(x_train,y_train)

Pipeline(steps=[('scaling', StandardScaler()), ('PCA', PCA(n_components=3)),
                ('classifier', SVC())])

In [69]:
pipe2.predict(x_test)

array([0, 0, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1])

<h1>Complex examples of columns transformer</h1>

In [72]:
#for numerix varaible to use impute
from sklearn.impute import SimpleImputer
from sklearn.pipeline import Pipeline

In [80]:
import numpy as np
numeric_processor=Pipeline(
    steps=[("imputation_mean",SimpleImputer(missing_values=np.nan,strategy="mean")),
     ("scaler",StandardScaler())]
)

In [81]:
numeric_processor

Pipeline(steps=[('imputation_mean', SimpleImputer()),
                ('scaler', StandardScaler())])

In [87]:
#Catagorical processing pipeline
from sklearn.preprocessing import OneHotEncoder
categorical_processor=Pipeline(
    steps=[("imputation_constant",SimpleImputer(fill_value="missing",strategy="contant")),
     ("onehot",OneHotEncoder(handle_unknown="ignore"))]
)

In [88]:
categorical_processor

Pipeline(steps=[('imputation_constant',
                 SimpleImputer(fill_value='missing', strategy='contant')),
                ('onehot', OneHotEncoder(handle_unknown='ignore'))])

In [89]:
#combine processing technques
from sklearn.compose import ColumnTransformer

In [93]:
preprocessor=ColumnTransformer(
    [("categorical",categorical_processor,["gender","city"]),
     ("numerical",numeric_processor,["age","height"])]
)

In [94]:
preprocessor

ColumnTransformer(transformers=[('categorical',
                                 Pipeline(steps=[('imputation_constant',
                                                  SimpleImputer(fill_value='missing',
                                                                strategy='contant')),
                                                 ('onehot',
                                                  OneHotEncoder(handle_unknown='ignore'))]),
                                 ['gender', 'city']),
                                ('numerical',
                                 Pipeline(steps=[('imputation_mean',
                                                  SimpleImputer()),
                                                 ('scaler', StandardScaler())]),
                                 ['age', 'height'])])

In [95]:
from sklearn.pipeline import make_pipeline

In [99]:
make_pipeline(preprocessor,LogisticRegression())
# make_pipeline(preprocessor,SVC())

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('categorical',
                                                  Pipeline(steps=[('imputation_constant',
                                                                   SimpleImputer(fill_value='missing',
                                                                                 strategy='contant')),
                                                                  ('onehot',
                                                                   OneHotEncoder(handle_unknown='ignore'))]),
                                                  ['gender', 'city']),
                                                 ('numerical',
                                                  Pipeline(steps=[('imputation_mean',
                                                                   SimpleImputer()),
                                                                  ('scaler',
                                                                   StandardScaler())]),
                                                  ['age', 'height'])])),
                ('logisticregression', LogisticRegression())])